FROM python:3.8-slim

RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm

WORKDIR /app

# Création requirement Pip install
COPY app_python/install /app
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install -r ./requirements.txt

COPY app_python/code /app

WORKDIR /codec
RUN npm i @adeunis/codecs

WORKDIR /app

#CMD ["python", "main.py"]
